name: Manually Build Image

on:
  workflow_dispatch:
    inputs:
      chroma-version:
        description: "Chroma version"
        required: true
        default: "0.4.24"
        type: string
      latest-version:
        description: "Latest Chroma version"
        required: true
        default: false
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "ghcr.io/amikos-tech/chromadb-chart/chroma"

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push release Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: image/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            CHROMA_VERSION=${{ github.event.inputs.chroma-version }}
          tags: "${{ env.IMAGE_NAME }}:${{ github.event.inputs.chroma-version }}"
      - name: Build and push release Docker image
        if: ${{ github.event.inputs.latest-version == true }}
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: image/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            CHROMA_VERSION=${{ github.event.inputs.chroma-version }}
          tags: "${{ env.IMAGE_NAME }}:${{ github.event.inputs.chroma-version }}, ${env.IMAGE_NAME}:latest"

