name: Release Charts

on:
  push:
    branches:
      - release
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "ghcr.io/amikos-tech/chromadb-chart/chroma"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        id: releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Latest release
        run: |
          echo "Latest release: ${{ steps.releaser.outputs.chart_version }}"
          echo "Changed charts: ${{ steps.releaser.outputs.changed_charts }}"
      - name: Log in to the Container registry
#        if: ${{ steps.releaser.outputs.changed_charts == '' }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push release Docker image
#        if: ${{ steps.releaser.outputs.changed_charts == '' }}
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: image/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: "${{ env.IMAGE_NAME }}:latest"